# Generated by Django 5.0.4 on 2024-04-14 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_locations_address2_alter_locations_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='location_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.locations'),
        ),
    ]
