# Generated by Django 5.0.4 on 2024-05-10 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_orders_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='Customers_id',
            new_name='customers_id',
        ),
    ]
