# Generated by Django 5.0.4 on 2024-05-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_rename_customers_id_orders_customers_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivered_date',
            field=models.DateField(default=None),
        ),
    ]
