# Generated by Django 5.0.4 on 2024-05-10 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('inventory_transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_order',
            fields=[
                ('purchase_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('recived_date', models.DateField()),
                ('tracking_number', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('storage_location_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('shelf_number', models.IntegerField()),
                ('level_number', models.IntegerField()),
                ('storage_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, upload_to='products/')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('price', models.DecimalField(decimal_places=2, default='0', max_digits=12)),
                ('cost', models.DecimalField(decimal_places=2, default='0', max_digits=12)),
                ('category_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventory.categories')),
            ],
            options={
                'db_table': 'inventory_product',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventorytransaction')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_items',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, default='0', max_digits=12)),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product')),
                ('purchase_order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.purchase_order')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('Inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product')),
                ('location_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.storagelocation')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default='0', max_digits=12)),
                ('lead_time', models.IntegerField()),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField()),
                ('category_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventory.categories')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsAndVendors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('vendor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.vendor')),
            ],
            options={
                'unique_together': {('product_id', 'vendor_id')},
            },
        ),
    ]
