# Generated by Django 5.0.4 on 2024-04-14 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, upload_to='products/')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('category_id', models.IntegerField(default='111')),
                ('price', models.DecimalField(decimal_places=11, default='0', max_digits=12)),
            ],
            options={
                'db_table': 'inventory_product',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
