# Generated by Django 5.0.4 on 2024-04-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_id',
            field=models.IntegerField(default='1'),
        ),
    ]
