# Generated by Django 4.2.11 on 2024-04-23 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_product_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase_order',
            fields=[
                ('purchase_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('recived_date', models.DateField()),
                ('tracking_number', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default='0', max_digits=12)),
                ('lead_time', models.IntegerField()),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_items',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, default='0', max_digits=12)),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product')),
                ('purchase_order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.purchase_order')),
            ],
        ),
    ]
